config/routes.rb
Rails.application.routes.draw do
  # get 'pockets/index'
  # get 'pockets/show'
  # get 'pockets/edit'
  # get 'pockets/new'
  # get 'payments/index'
  # get 'payments/show'
  # get 'payments/edit'
  # get 'payments/new'
  # get 'reports/index'
  # get 'reports/show'
  # get 'reports/edit'
  # get 'reports/new'
  # get 'teachers/index'
  # get 'teachers/show'
  # get 'teachers/edit'
  # get 'teachers/new'
  # get 'exams/index'
  # get 'exams/show'
  # get 'exams/edit'
  # get 'exams/new'
  root 'students#index'
  resources :students
  resources :exams
  resources :teachers
  resources :reports
  resources :payments
  resources :pockets
  # get 'students/index'
  # get 'students/show'
  # get 'students/edit'
  # get 'students/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/pocket.rb
class Pocket < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def index
    @exams = Exam.all
  end

  def show
    id = params[:id]
    @exam = Exam.find(id)
  end

  def edit
    id = params[:id]
    @exam = Exam.find(id)
  end

  def new
    @exam = Exam.new
  end

  def create
    exam = Exam.create(exam_params)
    flash[:notice] = "exam has been created"
    redirect_to exams_path
  end

  def update
    id = params[:id]
    exam = Exam.find(id)
    exam.update(exam_params)
    flash[:notice] = "exam has been updated"
    redirect_to exam_path(exam)
  end

  def destroy
    id = params[:id]
    exam = Exam.find(id)
    exam.destroy()
    flash[:notice] = "exam has been deleted"
    redirect_to exams_path
  end
  private
  def exam_params
    params.require(:exam).permit(:title, :mapel, :duration, :nilai, :status, :label, :student_id)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @payments = Payment.all
  end

  def show
    id = params[:id]
    @payment = Payment.find(id)
  end

  def edit
    id = params[:id]
    @payment = Payment.find(id)
  end

  def new
    @payment = Payment.new
  end

  def create
    payment = Payment.create(payment_params)
    flash[:notice] = "payment has been created"
    redirect_to payments_path
  end

  def update
    id = params[:id]
    payment = Payment.find(id)
    payment.update(payment_params)
    flash[:notice] = "payment has been updated"
    redirect_to payment_path(payment)
  end

  def destroy
    id = params[:id]
    payment = Payment.find(id)
    payment.destroy()
    flash[:notice] = "payment has been deleted"
    redirect_to payments_path
  end
  private
  def payment_params
    params.require(:payment).permit(:id_transaction, :status, :upload)
  end
end

app/controllers/pockets_controller.rb
class PocketsController < ApplicationController
  def index
    @pockets = Pocket.all
  end

  def show
    id = params[:id]
    @pocket = Pocket.find(id)
  end

  def edit
    id = params[:id]
    @pocket = Pocket.find(id)
  end

  def new
    @pocket = Pocket.new
  end

  def create
    pocket = Pocket.create(pocket_params)
    flash[:notice] = "pocket has been created"
    redirect_to pockets_path
  end

  def update
    id = params[:id]
    pocket = Pocket.find(id)
    pocket.update(pocket_params)
    flash[:notice] = "pocket has been updated"
    redirect_to pocket_path(pocket)
  end

  def destroy
    id = params[:id]
    pocket = Pocket.find(id)
    pocket.destroy()
    flash[:notice] = "pocket has been deleted"
    redirect_to pockets_path
  end
  private
  def pocket_params
    params.require(:pocket).permit(:balance, :student_id, :teacher_id)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Report.all
  end

  def show
    id = params[:id]
    @report = Report.find(id)
  end

  def edit
    id = params[:id]
    @report = Report.find(id)
  end

  def new
    @report = Report.new
  end

  def create
    report = Report.create(report_params)
    flash[:notice] = "report has been created"
    redirect_to reports_path
  end

  def update
    id = params[:id]
    report = Report.find(id)
    report.update(report_params)
    flash[:notice] = "report has been updated"
    redirect_to report_path(report)
  end

  def destroy
    id = params[:id]
    report = Report.find(id)
    report.destroy()
    flash[:notice] = "report has been deleted"
    redirect_to reports_path
  end
  private
  def report_params
    params.require(:report).permit(:title, :hasil, :mapel, :teacher_id, :student_id, :date)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    id = params[:id]
    @student = Student.find(id)
  end

  def edit
    id = params[:id]
    @student = Student.find(id)
  end

  def new
    @student = Student.new
  end

  def create
    student = Student.create(student_params)
    flash[:notice] = "Student has been created"
    redirect_to students_path
  end

  def update
    id = params[:id]
    student = Student.find(id)
    student.update(student_params)
    flash[:notice] = "Student has been updated"
    redirect_to student_path(student)
  end

  def destroy
    id = params[:id]
    student = Student.find(id)
    student.destroy()
    flash[:notice] = "Student has been deleted"
    redirect_to students_path
  end
  private
  def student_params
    params.require(:student).permit(:name, :kelas, :age, :username, :address, :city, :nik)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.all
  end

  def show
    id = params[:id]
    @teacher = Teacher.find(id)
  end

  def edit
    id = params[:id]
    @teacher = Teacher.find(id)
  end

  def new
    @teacher = Teacher.new
  end

  def create
    teacher = Teacher.create(teacher_params)
    flash[:notice] = "teacher has been created"
    redirect_to teachers_path
  end

  def update
    id = params[:id]
    teacher = Teacher.find(id)
    teacher.update(teacher_params)
    flash[:notice] = "teacher has been updated"
    redirect_to teacher_path(teacher)
  end

  def destroy
    id = params[:id]
    teacher = Teacher.find(id)
    teacher.destroy()
    flash[:notice] = "teacher has been deleted"
    redirect_to teachers_path
  end
  private
  def teacher_params
    params.require(:teacher).permit(:nik, :name, :age, :kelas, :mapel)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/pockets_helper.rb
module PocketsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/exams/edit.html.erb
<%= form_for(@exam) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>

    <%= f.label :nilai %> </br>
    <%= f.text_field :nilai %> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>

    <%= f.label :level %> </br>
    <%= f.text_field :level %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>


    <%= f.submit "Update" %>
<% end %>
</br>
<%= link_to 'back to table exam', exams_path %>

app/views/exams/index.html.erb
<% if flash[:notice].present?%>
    <%= flash[:notice] %> 
<% end %> </br>
<table class="table" border="1">
    <thead class="thead-dark">
        <tr>
            <th>Title</th>
            <th>Mapel</th>
            <th>Duration</th>
            <th>Nilai</th>
            <th>Status</th>
            <th>Level</th>
            <th>Student_ID</th>
            <th colspan="3" style="text-align:center">Action</th>
        </tr>
    </thead>
    <% @exams.each do |item| %>
        <tr>
            <td><%= item.title %></td>
            <td><%= item.mapel %></td>
            <td><%= item.duration %></td>
            <td><%= item.nilai %></td>
            <td><%= item.status %></td>
            <td><%= item.level %></td>
            <td><%= item.student_id %></td>
            <td><%= link_to 'Detail', exam_path(item) %></td>
            <td><%= link_to 'Edit', edit_exam_path(item) %></td>
            <td><%= link_to 'Delete', exam_path(item), method: :delete, data:{confirm:"Apa anda yakin akan menghapus data ini ?"} %></td>
        </tr>
    <% end %>
</table>
<%= link_to 'Create', new_exam_path %>

app/views/exams/new.html.erb
<%= form_for(@exam) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>

    <%= f.label :nilai %> </br>
    <%= f.text_field :nilai %> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>

    <%= f.label :level %> </br>
    <%= f.text_field :level %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>


    <%= f.submit "Save" %>
<% end %>
</br>
<%= link_to 'back to table exam', exams_path %>

app/views/exams/show.html.erb
<% if flash[:notice].present?%>
    <%= flash[:notice] %> 
<% end %> </br>

title : <%=  @exam.title %> </br>
mapel : <%= @exam.mapel %> </br>
duration : <%= @exam.duration %> </br>
nilai : <%= @exam.nilai %> </br>
status : <%= @exam.status %> </br>
level : <%= @exam.level %> </br>
student_id : <%= @exam.student_id %> </br>

<%= link_to 'back to table exam', exams_path %>

app/views/payments/edit.html.erb
<%= form_for(@payment) do |f| %>
    <%= f.label :id_transaction %> </br>
    <%= f.text_field :id_transaction %> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>

    <%= f.label :upload %> </br>
    <%= f.text_field :upload %> </br>

    <%= f.submit "Update" %>
<% end %>
</br>
<%= link_to 'back to table payment', payments_path %>

app/views/payments/index.html.erb
<% if flash[:notice].present?%>
    <%= flash[:notice] %> 
<% end %> </br>
<table class="table" border="1">
    <thead class="thead-dark">
    <tr>
        <th>ID_Transaction</th>
        <th>status</th>
        <th>upload</th>
        <th colspan="3" style="text-align:center">Action</th>
    </tr>
    </thead>
    <% @payments.each do |item| %>
        <tr>
            <td><%= item.id_transaction %></td>
            <td><%= item.status %></td>
            <td><%= item.upload %></td>
            <td><%= link_to 'Detail', payment_path(item) %></td>
            <td><%= link_to 'Edit', edit_payment_path(item) %></td>
            <td><%= link_to 'Delete', payment_path(item), method: :delete, data:{confirm:"Apa anda yakin akan menghapus data ini ?"} %></td>
        </tr>
    <% end %>
</table>
<%= link_to 'Create', new_payment_path %>

app/views/payments/new.html.erb
<%= form_for(@payment) do |f| %>
    <%= f.label :id_transaction %> </br>
    <%= f.text_field :id_transaction %> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>

    <%= f.label :upload %> </br>
    <%= f.text_field :upload %> </br>

    <%= f.submit "Save" %>
<% end %>
</br>
<%= link_to 'back to table payment', payments_path %>

app/views/payments/show.html.erb
<% if flash[:notice].present?%>
    <%= flash[:notice] %> 
<% end %> </br>

id_transaction : <%=  @payment.id_transaction %> </br>
status : <%= @payment.status %> </br>
upload : <%= @payment.upload %> </br>

<%= link_to 'back to table payment', payments_path %>

app/views/pockets/edit.html.erb
<%= form_for(@pocket) do |f| %>
    <%= f.label :balance %> </br>
    <%= f.text_field :balance %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>

    <%= f.label :teacher_id %> </br>
    <%= f.text_field :teacher_id %> </br>

    <%= f.submit "Update" %>
<% end %>
</br>
<%= link_to 'back to table pocket', pockets_path %>

app/views/pockets/index.html.erb
<% if flash[:notice].present?%>
    <%= flash[:notice] %> 
<% end %> </br>
<table class="table" border="1">
    <thead class="thead-dark">
        <tr>
            <th>balance</th>
            <th>student_id</th>
            <th>teacher_id</th>
            <th colspan="3" style="text-align:center">Action</th>
        </tr>
    </thead>
    <% @pockets.each do |item| %>
        <tr>
            <td><%= item.balance %></td>
            <td><%= item.student_id %></td>
            <td><%= item.teacher_id %></td>
            <td><%= link_to 'Detail', pocket_path(item) %></td>
            <td><%= link_to 'Edit', edit_pocket_path(item) %></td>
            <td><%= link_to 'Delete', pocket_path(item), method: :delete, data:{confirm:"Apa anda yakin akan menghapus data ini ?"} %></td>
        </tr>
    <% end %>
</table>
<%= link_to 'Create', new_pocket_path %>

app/views/pockets/new.html.erb
<%= form_for(@pocket) do |f| %>
    <%= f.label :balance %> </br>
    <%= f.text_field :balance %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>

    <%= f.label :teacher_id %> </br>
    <%= f.text_field :teacher_id %> </br>

    <%= f.submit "Save" %>
<% end %>
</br>
<%= link_to 'back to table pocket', pockets_path %>

app/views/pockets/show.html.erb
<% if flash[:notice].present?%>
    <%= flash[:notice] %> 
<% end %> </br>

balance : <%=  @pocket.balance %> </br>
student_id : <%= @pocket.student_id %> </br>
teacher_id : <%= @pocket.teacher_id %> </br>

<%= link_to 'back to table pocket', pockets_path %>

app/views/reports/edit.html.erb
<%= form_for(@report) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>

    <%= f.label :hasil %> </br>
    <%= f.text_field :hasil %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :teacher_id %> </br>
    <%= f.text_field :teacher_id %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>

    <%= f.label :date %> </br>
    <%= f.date_field :date %> </br>

    <%= f.submit "Update" %>
<% end %>
</br>
<%= link_to 'back to table report', reports_path %>

app/views/reports/index.html.erb
<% if flash[:notice].present?%>
    <%= flash[:notice] %> 
<% end %> </br>
<table class="table" border="1">
    <thead class="thead-dark">
        <tr>
            <th>Title</th>
            <th>Hasil</th>
            <th>Mapel</th>
            <th>Teacher_ID</th>
            <th>Student_ID</th>
            <th>date</th>
            <th colspan="3" style="text-align:center">Action</th>
        </tr>
    </thead>
    <% @reports.each do |item| %>
        <tr>
            <td><%= item.title %></td>
            <td><%= item.hasil %></td>
            <td><%= item.mapel %></td>
            <td><%= item.teacher_id %></td>
            <td><%= item.student_id %></td>
            <td><%= item.date %></td>
            <td><%= link_to 'Detail', report_path(item) %></td>
            <td><%= link_to 'Edit', edit_report_path(item) %></td>
            <td><%= link_to 'Delete', report_path(item), method: :delete, data:{confirm:"Apa anda yakin akan menghapus data ini ?"} %></td>
        </tr>
    <% end %>
</table>
<%= link_to 'Create', new_report_path %>

app/views/reports/new.html.erb
<%= form_for(@report) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>

    <%= f.label :hasil %> </br>
    <%= f.text_field :hasil %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :teacher_id %> </br>
    <%= f.text_field :teacher_id %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>

    <%= f.label :date %> </br>
    <%= f.date_field :date %> </br>

    <%= f.submit "Save" %>
<% end %>
</br>
<%= link_to 'back to table report', reports_path %>

app/views/reports/show.html.erb
<% if flash[:notice].present?%>
    <%= flash[:notice] %> 
<% end %> </br>

title : <%=  @report.title %> </br>
hasil : <%= @report.hasil %> </br>
mapel : <%= @report.mapel %> </br>
teacher_id : <%= @report.teacher_id %> </br>
student_id : <%= @report.student_id %> </br>
date : <%= @report.date %> </br>

<%= link_to 'back to table report', reports_path %>

app/views/students/edit.html.erb
<%= form_for(@student) do |f| %>
    <%= f.label :name %> </br>
    <%= f.text_field :name %> </br>

    <%= f.label :username %> </br>
    <%= f.text_field :username %> </br>

    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas %> </br>

    <%= f.label :age %> </br>
    <%= f.text_field :age %> </br>

    <%= f.label :address %> </br>
    <%= f.text_field :address %> </br>

    <%= f.label :city %> </br>
    <%= f.text_field :city %> </br>

    <%= f.label :nik %> </br>
    <%= f.text_field :nik %> </br>


    <%= f.submit "Update" %>
<% end %>
</br>
<%= link_to 'back to table student', students_path %>

app/views/students/index.html.erb
<% if flash[:notice].present?%>
    <%= flash[:notice] %> 
<% end %> </br>
<table class="table" border="1">
<thead class="thead-dark">
    <tr>
        <th>Name</th>
        <th>Username</th>
        <th>Kelas</th>
        <th>Age</th>
        <th>Address</th>
        <th>City</th>
        <th>NIK</th>
        <th colspan="3" style="text-align:center">Action</th>
    </tr>
</thead>
    <% @students.each do |item| %>
        <tr>
            <td><%= item.name %></td>
            <td><%= item.username %></td>
            <td><%= item.kelas %></td>
            <td><%= item.age %></td>
            <td><%= item.address %></td>
            <td><%= item.city %></td>
            <td><%= item.nik %></td>
            <td><%= link_to 'Detail', student_path(item) %></td>
            <td><%= link_to 'Edit', edit_student_path(item) %></td>
            <td><%= link_to 'Delete', student_path(item), method: :delete, data:{confirm:"Apa anda yakin akan menghapus data ini ?"} %></td>
        </tr>
    <% end %>
</table>
<%= link_to 'Create', new_student_path %>

app/views/students/new.html.erb
<%= form_for(@student) do |f| %>
    <%= f.label :name %> </br>
    <%= f.text_field :name %> </br>

    <%= f.label :username %> </br>
    <%= f.text_field :username %> </br>

    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas %> </br>

    <%= f.label :age %> </br>
    <%= f.text_field :age %> </br>

    <%= f.label :address %> </br>
    <%= f.text_field :address %> </br>

    <%= f.label :city %> </br>
    <%= f.text_field :city %> </br>

    <%= f.label :nik %> </br>
    <%= f.text_field :nik %> </br>


    <%= f.submit "Save" %>
<% end %>
</br>
<%= link_to 'back to table student', students_path %>

app/views/students/show.html.erb
<% if flash[:notice].present?%>
    <%= flash[:notice] %> 
<% end %> </br>

name : <%=  @student.name %> </br>
username : <%= @student.username %> </br>
kelas : <%= @student.kelas %> </br>
age : <%= @student.age %> </br>
address : <%= @student.address %> </br>
city : <%= @student.city %> </br>
nik : <%= @student.nik %> </br>

<%= link_to 'back to table student', students_path %>

app/views/teachers/edit.html.erb
<%= form_for(@teacher) do |f| %>
    <%= f.label :nik %> </br>
    <%= f.text_field :nik %> </br>

    <%= f.label :name %> </br>
    <%= f.text_field :name %> </br>

    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas %> </br>

    <%= f.label :age %> </br>
    <%= f.text_field :age %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.submit "Update" %>
<% end %>
</br>
<%= link_to 'back to table teacher', teachers_path %>

app/views/teachers/index.html.erb
<% if flash[:notice].present?%>
    <%= flash[:notice] %> 
<% end %> </br>
<table class="table" border="1">
    <thead class="thead-dark">
        <tr>
            <th>NIK</th>
            <th>Name</th>
            <th>Kelas</th>
            <th>Age</th>
            <th>Mapel</th>
            <th colspan="3" style="text-align:center">Action</th>
        </tr>
    </thead>
    <% @teachers.each do |item| %>
        <tr>
            <td><%= item.nik %></td>
            <td><%= item.name %></td>
            <td><%= item.kelas %></td>
            <td><%= item.age %></td>
            <td><%= item.mapel %></td>
            <td><%= link_to 'Detail', teacher_path(item) %></td>
            <td><%= link_to 'Edit', edit_teacher_path(item) %></td>
            <td><%= link_to 'Delete', teacher_path(item), method: :delete, data:{confirm:"Apa anda yakin akan menghapus data ini ?"} %></td>
        </tr>
    <% end %>
</table>
<%= link_to 'Create', new_teacher_path %>

app/views/teachers/new.html.erb
<%= form_for(@teacher) do |f| %>
    <%= f.label :nik %> </br>
    <%= f.text_field :nik %> </br>

    <%= f.label :name %> </br>
    <%= f.text_field :name %> </br>

    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas %> </br>

    <%= f.label :age %> </br>
    <%= f.text_field :age %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.submit "Save" %>
<% end %>
</br>
<%= link_to 'back to table teacher', teachers_path %>

app/views/teachers/show.html.erb
<% if flash[:notice].present?%>
    <%= flash[:notice] %> 
<% end %> </br>

nik : <%=  @teacher.nik %> </br>
name : <%= @teacher.name %> </br>
kelas : <%= @teacher.kelas %> </br>
age : <%= @teacher.age %> </br>
mapel : <%= @teacher.mapel %> </br>

<%= link_to 'back to table teacher', teachers_path %>